### ISSUE TITLE
Support multiple counters on one page

### ISSUE THREAD

**Issue by JamesSkemp** [dtisgodsson/jquery-character-counter#10]
I have a form that has over 20 fields on it that need to have a character counter displayed.

Calling `$("textarea").characterCounter();` results in each textarea getting a counter, but they all share the same value.

Same issue if I attach characterCounter() to two different ids.

It would be awesome if this supported the ability to add counters for multiple fields on one page.

**Comment by dtisgodsson** [comment]
@JamesSkemp sorry you're experiencing this issue.

I'll hopefully have a look at that today and try get it sorted.

**Comment by neuropass** [comment]
+1 This would be great.

**Comment by dtisgodsson** [comment]
@JamesSkemp @neuropass sorry for the delay - I've pushed a change which will fix this issue.

Cheers,
Darren

**Comment by JamesSkemp** [comment]
Sorry Darren, took a few days to get back to the project.

Works great! Thanks for the quick turnaround and addition!

**Comment by dtisgodsson** [comment]
Glad it's working fine @JamesSkemp

Cheers,
Darren
