### ISSUE TITLE
semantic versioning

### ISSUE THREAD

**Issue by neuropass** [dtisgodsson/jquery-character-counter#11]
Hi,

Can you add semantic version to the file? Now it says 1.x, a old version I have says 1.0.

Should be something like 1.0.1, 1.2.0 etc etc.

Thanks!

**Comment by dtisgodsson** [comment]
@neuropass I've now versioned the file and the commit as v1.5.0 and subsequent versions will be versioned accordingly.

Thanks,
Darren
