### ISSUE TITLE
Error in IE8

### ISSUE THREAD

**Issue by jj2fowler** [dtisgodsson/jquery-character-counter#12]
The following error is thrown when calling the characterCounter() in IE8 (e.g. $('#textareaID').characterCounter({ ...options... }) ):

Expected identifier
Object doesn't support this property or method

I'm not sure if you are aiming to support IE8 as I couldn't see any supported browser details, so I'm not sure if this is really a problem. I've tried to identify which property or method is the offender but have been unable to find it thus far. Hopefully someone else more knowledgeable than me might be able to figure it out.

**Comment by jj2fowler** [comment]
I think I've got it narrowed down to the following function:

function generateCounter()
{
  var classString = options.counterCssClass;

  if ( options.customFields.class )
  {
    classString += " " + options.customFields.class;
    delete options.customFields['class'];
  }

  return '<'+ options.counterWrapper +customFields(options.customFields)+' class="' + classString + '"></'+ options.counterWrapper +'>';
}

**Comment by jj2fowler** [comment]
It's this line in particular that is causing the issue in IE8: options.customFields.class

I'm not declaring any classes for this so I have just commented it out for now.

I also found that $(element).bind("keyup", function () {... in the bindEvents function had to be changed to $(element).on("keyup", function () {... to get it working properly in IE8.

Again, this may be of no concern to you as you never intended it to be compatible with IE8 but I thought I would make a note of it regardless.

**Comment by dtisgodsson** [comment]
Thanks for the bug report @jj2fowler 

I'll try and have a look at it next time I'm on my Windows machine.

**Comment by jacobmmartin** [comment]
it appears that ie sees .class as a keyword. Any updates on this?

**Comment by dtisgodsson** [comment]
@jj2fowler, @wardtwits has fixed this issue - IE8 has some issues with dot notations.

This has been merged into develop and will hopefully solve any problems you're having in IE8.
