### ISSUE TITLE
Conflict when using jquery validate

### ISSUE THREAD

**Issue by Jrizzi1** [dtisgodsson/jquery-character-counter#13]
Take a look at my example, the counter works fine unless you hit submit and validation error fires, the counter stops working after the first error occurs on a field

http://jsfiddle.net/4k1vokgv/1/

try typing in the first textarea and hit submit, notice the first textarea's counter still will work, but the second textarea counter will not work even if validation is ok

I am just trying to figure out the conflict or the event that is halting the counter

**Comment by dtisgodsson** [comment]
Thanks for this @Jrizzi1 - I'll try to fix this as soon as I can.

Cheers,
Darren

**Comment by Jrizzi1** [comment]
I apologize, i went to go make a branch and fix the issue, but realized I was not using the most recent update of the script, the demo page http://www.jqueryscript.net/demo/Twitter-Like-Text-Box-Character-Counter-with-jQuery-Bootstrap/ has the 1.0 version, once i upgraded to 1.5.1 this issue went away

http://jsfiddle.net/4k1vokgv/3/
