### ISSUE TITLE
Reset counter

### ISSUE THREAD

**Issue by liammcsheffrey** [dtisgodsson/jquery-character-counter#8]
Hi,

Is there a callback to reset / refresh the counter?

Thanks

**Comment by dtisgodsson** [comment]
Hi @liammcsheffrey,

Do you mean triggering a re-count should you, for example, dynamically manipulate the contents of a countable field?

In which case, there is no way of triggering a refresh but one I could certainly add.

Cheers,
Darren

**Comment by dtisgodsson** [comment]
Closing this.
